pub enum Instruction {
    Stc,
    Cmc,
    Inr  { reg:   u8 },
    Dcr  { reg:   u8 },
    Cma,
    Daa,
    Nop,
    Mov  { dst:   u8, src:   u8 },
    Stax { rp:    u8 },
    Ldax { rp:    u8 },
    Add  { reg:   u8 },
    Adc  { reg:   u8 },
    Sub  { reg:   u8 },
    Sbb  { reg:   u8 },
    Ana  { reg:   u8 },
    Xra  { reg:   u8 },
    Ora  { reg:   u8 },
    Cmp  { reg:   u8 },
    Rlc,
    Rrc,
    Ral,
    Rar,
    Push { rp:    u8 },
    Pop  { rp:    u8 },
    Dad  { rp:    u8 },
    Inx  { rp:    u8 },
    Dcx  { rp:    u8 },
    Xchg,
    Xthl,
    Sphl,
    Lxi  { rp:    u8, data: u16 },
    Mvi  { reg:   u8, data: u8  },
    Adi  { data:  u8 },
    Aci  { data:  u8 },
    Sui  { data:  u8 },
    Sbi  { data:  u8 },
    Ani  { data:  u8 },
    Xri  { data:  u8 },
    Ori  { data:  u8 },
    Cpi  { data:  u8 },
    Sta  { exp:  u16 },
    Lda  { exp:  u16 },
    Shld { exp:  u16 },
    Lhld { exp:  u16 },
    Pchl,
    Jmp  { exp:  u16 },
    Jc   { exp:  u16 },
    Jnc  { exp:  u16 },
    Jz   { exp:  u16 },
    Jnz  { exp:  u16 },
    Jm   { exp:  u16 },
    Jp   { exp:  u16 },
    Jpe  { exp:  u16 },
    Jpo  { exp:  u16 },
    Call { sub:  u16 },
    Cc   { sub:  u16 },
    Cnc  { sub:  u16 },
    Cz   { sub:  u16 },
    Cnz  { sub:  u16 },
    Cm   { sub:  u16 },
    Cp   { sub:  u16 },
    Cpe  { sub:  u16 },
    Cpo  { sub:  u16 },
    Ret,
    Rc,
    Rnc,
    Rnz,
    Rz,
    Rm,
    Rp,
    Rpe,
    Rpo,
    Rst  { exp:   u8 },
    Ei,
    Di,
    In   { exp:   u8 },
    Out  { exp:   u8 },
    Hlt,
}
